#cloud-config

package_update: true
package_upgrade: true

packages:
  - awscli

write_files:
  - path: /tmp/install-k3s.sh
    permissions: '0755'
    owner: root:root
    content: |
      #!/bin/bash

      set -e

      amazon-linux-extras enable selinux-ng
      yum clean metadata
      yum install selinux-policy-targeted -y

      check_master_ready() {
        aws ec2 describe-instance-status \
          --instance-ids ${server_instance_id} \
          --query 'InstanceStatuses[0].InstanceStatus.Status' \
          --output text \
          --region ${aws_region} | grep -q "ok"
      }

      export -f check_master_ready
      export aws_region
      export server_instance_id

      timeout 300 bash -c 'until check_master_ready; do sleep 10; done'

      if systemctl is-active --quiet k3s-agent; then
        systemctl stop k3s-agent
      fi

      if [ -f /usr/local/bin/k3s-agent-uninstall.sh ]; then
        /usr/local/bin/k3s-agent-uninstall.sh
      fi

      TOKEN=$(aws ssm get-parameter --name "${ssm_parameter_name}" --with-decryption --query Parameter.Value --output text --region "${aws_region}")
      curl -sfL https://get.k3s.io | K3S_URL="https://${master_ip}:6443" K3S_TOKEN="$TOKEN" sh -s - agent

runcmd:
  - "bash -c 'sudo /tmp/install-k3s.sh'"
